### PR TITLE
corrected error in ServerSideAES256 and Forced Encryption config, 

### PR DESCRIPTION
**Pull request by agstevens**
- corrected (serious) error in ServerSideAES256 and Forced Encryption config
- Added Privacy filter back for the s3 buckets (the error was related to the Forced Encryption mistake above)
- added georestriction in cloudfront
- added basic lifecycle rules for the photos in storage to optimize storage costs after 30 days
- modified resize function to put objects using AES256 encryption.
- The photo data is properly protected at rest now!

### CODE REVIEW

**Comment by jpsim** [comment]
> added georestriction in cloudfront

Why restrict to just US? Is this because you don’t expect non-US visitors in your installation? Most of my legitimate visitors are non-US.

**Comment by agstevens** [comment]
For me, yes.  I recognize that many people from around the world probably use this and having that as a default setting is probably silly for them, so perhaps it would be best to comment that out in the master version on github (or remove it) and people can enable it if they expect visitors from only a few countries or wanted to blacklist a particular country. 

Thanks for your work on this project by the way. I'm learning a lot from this.

**Comment by jpsim** [comment]
> perhaps it would be best to comment that out in the master version on github

Yes, can you please do that?

**Comment by agstevens** [comment]
- Sure thing. Commented out Georestrictions - they are left in as an example.
- Updated Documentation.
- Debugged the SiteBuilder - it was running into the 3500 writes/sec rate limit for S3, which occurs in the case of more than ~116 folders. Inserted a ~100ms delay in the album write function and some logging, and improved the truncated listing handling. This will scale better now going forward.

**Comment by agstevens** [comment]
Just ran one more test deployment and it worked fine, updated documentation once more. Ready to merge pull request.

**Pull request merged**
