### PR TITLE
new feature -- Google Analytics

### PR DESCRIPTION
**Pull request by jsloan117**
I wanted Google Analytics on my own non-password protected version of this project and thought others might as well.

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for the PR! Would it be possible to only load the analytics script if a GA Key is provided?

I can see how someone may want this, but personally I’d rather not send my users’ data to google for each page load.

**Comment by jsloan117** [comment]
I'll review the code and make the requested changes.

**Comment by jsloan117** [comment]
@jpsim As requested these changes have been made. I don't know NodeJS but was able to Google my way through this.

Changes:

- Google Analytics to main, albums, error pages
- Switched to NodeJS 8.10 because 6.10 will be EOL and I believe removed by AWS at end of this month. I've been using 8.10 on my own passwordless version of this project and have not seen any issues related to moving to 8.10.

**Comment by jpsim** [comment]
Looks good now, thanks so much!

**Pull request merged**
